export enum ApiPath {
  SUBJECTS = "/subjects",
  QUESTIONS = "/questions",
  USERS = "/users",
  ADMIN = "/admin",
  TEST_SUBJECT = "/tests/subject",
  TEST = "/tests",
  ROLES = "/roles",
  ARTICLES = "/articles",
  REVIEWS = "/reviews",
  ORDERS = "/orders",
  FLASH_SALES = "/flashsales",
  BOOKS = "/books",
  CATEGORIES = "/categories",
  VOUCHERS = "/vouchers",
  SHOPS = "/shops",
  SHOP_BOOKS = "/shop-books",
  STAFF = "/staffs",
  PROVINCES = "/provinces",
  DISTRICTS = "/districts",
  WARDS = "/wards",
}
